spring.application.name=receta-api

spring.datasource.url=jdbc:h2:mem:receta-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Usuario admin (solo para POST/PUT/DELETE)
spring.security.user.name=admin
spring.security.user.password=12
spring.security.user.roles=ADMIN

#  OpenFDA base url (sin label.json)
external.meds.base-url=https://api.fda.gov/drug

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.client=DEBUG
logging.level.org.springframework.security=DEBUG