INSERT INTO PATIENTS (FULL_NAME, AGE, DIAGNOSIS)
VALUES ('Juan Perez', 32, 'dolor de cabeza');

INSERT INTO PATIENTS (FULL_NAME, AGE, DIAGNOSIS)
VALUES ('Maria Lopez', 24, 'alergia');

INSERT INTO PATIENTS (FULL_NAME, AGE, DIAGNOSIS)
VALUES ('Carlos Ramirez', 45, 'fiebre');

INSERT INTO PATIENTS (FULL_NAME, AGE, DIAGNOSIS)
VALUES ('Marco', 45, 'Alcoholismo');